columns:
  - person_age: int
  - person_income: int
  - person_home_ownership: category
  - person_emp_length: float
  - loan_intent: category
  - loan_grade: category
  - loan_amnt: int
  - loan_int_rate: float
  - loan_status: int
  - loan_percent_income: float
  - cb_person_default_on_file: category
  - cb_person_cred_hist_length: int


numerical_columns:
  - person_age
  - person_income
  - person_emp_length
  - loan_amnt
  - loan_int_rate
  - loan_status
  - loan_percent_income
  - cb_person_cred_hist_length

categorical_columns:
  - person_home_ownership
  - loan_intent
  - loan_grade
  - cb_person_default_on_file

drop_columns: _id

# for data transformation
cap_columns:
  person_emp_length: 40

impute_columns:
  - person_emp_length: median
  - loan_int_rate: median

one_hot_columns:
  - person_home_ownership
  - loan_intent

ordinal_columns:
  loan_grade:
    categories: ["G", "F", "E", "D", "C", "B", "A"]

#boolean_columns:
#  - cb_person_default_on_file



#cap_columns:
#  person_emp_length: 40

#impute_columns:
#  - person_emp_length: median
#  - loan_int_rate: median

#one_hot_columns:
#  - person_home_ownership
#  - loan_intent

#ordinal_columns:
#  loan_grade:
#    categories: ["G", "F", "E", "D", "C", "B", "A"]

#boolean_columns:
#  - person_home_ownership
#  - loan_intent


#num_features:
#  - Age
#  - Vintage


#mm_columns:
#  - Annual_Premium